CREATE TABLE IF NOT EXISTS event (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    guild TEXT NOT NULL,
    creator TEXT NOT NULL,
    channel TEXT NOT NULL,
    messages TEXT[] NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);