/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 3.4.0.0
 */
using System.Collections.Generic;
using System.IO;
using Hime.Redist;
using Hime.Redist.Lexer;

namespace E
{
	/// <summary>
	/// Represents a lexer
	/// </summary>
	internal class ELexer : ContextFreeLexer
	{
		/// <summary>
		/// The automaton for this lexer
		/// </summary>
		private static readonly Automaton commonAutomaton = Automaton.Find(typeof(ELexer), "ELexer.bin");
		/// <summary>
		/// Contains the constant IDs for the terminals for this lexer
		/// </summary>
		public class ID
		{
			/// <summary>
			/// The unique identifier for terminal WHITE_SPACE
			/// </summary>
			public const int TerminalWhiteSpace = 0x0003;
			/// <summary>
			/// The unique identifier for terminal SEPARATOR
			/// </summary>
			public const int TerminalSeparator = 0x0004;
			/// <summary>
			/// The unique identifier for terminal E
			/// </summary>
			public const int TerminalE = 0x0005;
			/// <summary>
			/// The unique identifier for terminal DIGIT
			/// </summary>
			public const int TerminalDigit = 0x0006;
			/// <summary>
			/// The unique identifier for terminal NONZERO
			/// </summary>
			public const int TerminalNonzero = 0x0007;
			/// <summary>
			/// The unique identifier for terminal INTEGER
			/// </summary>
			public const int TerminalInteger = 0x0008;
			/// <summary>
			/// The unique identifier for terminal HOUR
			/// </summary>
			public const int TerminalHour = 0x0009;
			/// <summary>
			/// The unique identifier for terminal MINUTE
			/// </summary>
			public const int TerminalMinute = 0x000A;
			/// <summary>
			/// The unique identifier for terminal YFINAL
			/// </summary>
			public const int TerminalYfinal = 0x000B;
			/// <summary>
			/// The unique identifier for terminal NUMBER
			/// </summary>
			public const int TerminalNumber = 0x000C;
			/// <summary>
			/// The unique identifier for terminal TEXTTIME
			/// </summary>
			public const int TerminalTexttime = 0x000D;
			/// <summary>
			/// The unique identifier for terminal N
			/// </summary>
			public const int TerminalN = 0x000E;
			/// <summary>
			/// The unique identifier for terminal AT_OR_BEFORE
			/// </summary>
			public const int TerminalAtOrBefore = 0x000F;
			/// <summary>
			/// The unique identifier for terminal WITHIN
			/// </summary>
			public const int TerminalWithin = 0x0010;
			/// <summary>
			/// The unique identifier for terminal IN
			/// </summary>
			public const int TerminalIn = 0x0011;
			/// <summary>
			/// The unique identifier for terminal LIKE
			/// </summary>
			public const int TerminalLike = 0x0012;
			/// <summary>
			/// The unique identifier for terminal EVENTUALLY
			/// </summary>
			public const int TerminalEventually = 0x0013;
			/// <summary>
			/// The unique identifier for terminal TONIGHT
			/// </summary>
			public const int TerminalTonight = 0x0014;
			/// <summary>
			/// The unique identifier for terminal SOON
			/// </summary>
			public const int TerminalSoon = 0x0015;
			/// <summary>
			/// The unique identifier for terminal SOONISH
			/// </summary>
			public const int TerminalSoonish = 0x0016;
			/// <summary>
			/// The unique identifier for terminal MIN
			/// </summary>
			public const int TerminalMin = 0x0017;
			/// <summary>
			/// The unique identifier for terminal MINS
			/// </summary>
			public const int TerminalMins = 0x0018;
			/// <summary>
			/// The unique identifier for terminal AMINUTE
			/// </summary>
			public const int TerminalAminute = 0x0019;
			/// <summary>
			/// The unique identifier for terminal ANHOUR
			/// </summary>
			public const int TerminalAnhour = 0x001A;
			/// <summary>
			/// The unique identifier for terminal RANGE
			/// </summary>
			public const int TerminalRange = 0x001B;
		}
		/// <summary>
		/// Contains the constant IDs for the contexts for this lexer
		/// </summary>
		public class Context
		{
			/// <summary>
			/// The unique identifier for the default context
			/// </summary>
			public const int Default = 0;
		}
		/// <summary>
		/// The collection of terminals matched by this lexer
		/// </summary>
		/// <remarks>
		/// The terminals are in an order consistent with the automaton,
		/// so that terminal indices in the automaton can be used to retrieve the terminals in this table
		/// </remarks>
		private static readonly Symbol[] terminals = {
			new Symbol(0x0001, "ε"),
			new Symbol(0x0002, "$"),
			new Symbol(0x0003, "WHITE_SPACE"),
			new Symbol(0x0004, "SEPARATOR"),
			new Symbol(0x0005, "E"),
			new Symbol(0x0006, "DIGIT"),
			new Symbol(0x0007, "NONZERO"),
			new Symbol(0x0008, "INTEGER"),
			new Symbol(0x0009, "HOUR"),
			new Symbol(0x000A, "MINUTE"),
			new Symbol(0x000B, "YFINAL"),
			new Symbol(0x000C, "NUMBER"),
			new Symbol(0x000D, "TEXTTIME"),
			new Symbol(0x000E, "N"),
			new Symbol(0x000F, "AT_OR_BEFORE"),
			new Symbol(0x0010, "WITHIN"),
			new Symbol(0x0011, "IN"),
			new Symbol(0x0012, "LIKE"),
			new Symbol(0x0013, "EVENTUALLY"),
			new Symbol(0x0014, "TONIGHT"),
			new Symbol(0x0015, "SOON"),
			new Symbol(0x0016, "SOONISH"),
			new Symbol(0x0017, "MIN"),
			new Symbol(0x0018, "MINS"),
			new Symbol(0x0019, "AMINUTE"),
			new Symbol(0x001A, "ANHOUR"),
			new Symbol(0x001B, "RANGE"),
			new Symbol(0x002A, ":"),
			new Symbol(0x002B, " "),
			new Symbol(0x002C, "hr"),
			new Symbol(0x002D, " hour"),
			new Symbol(0x002E, "s"),
			new Symbol(0x002F, "a "),
			new Symbol(0x0030, "bit"),
			new Symbol(0x0031, "couple"),
			new Symbol(0x0032, "of "),
			new Symbol(0x0033, "few"),
			new Symbol(0x0034, " a while"),
			new Symbol(0x0035, " now"),
			new Symbol(0x0036, "mm"),
			new Symbol(0x0037, "d"),
			new Symbol(0x0038, "i"),
			new Symbol(0x0039, "atel"),
			new Symbol(0x003A, " tonight"),
			new Symbol(0x003B, " later"),
			new Symbol(0x003C, "?") };
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public ELexer(string input) : base(commonAutomaton, terminals, 0x0004, input) {}
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public ELexer(TextReader input) : base(commonAutomaton, terminals, 0x0004, input) {}
	}
}
